stages:
  - sync

sync:
  stage: sync
  image: zaporylie/git
  script:
    - ssh-keyscan -H ${GIT_SYNC_REMOTE_HOST} >> ~/.ssh/known_hosts
    - git remote rm sync || true
    - git remote add sync ${GIT_SYNC_REMOTE_URL}
    - git checkout ${CI_BUILD_REF_NAME}
    - git pull origin ${CI_BUILD_REF_NAME}
    - git push sync ${CI_BUILD_REF_NAME}
  tags:
    - docker-build