version: '2'
services:
    db:
        image: mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: 'cakephp'
          MYSQL_DATABASE: 'cakephp'
    php:
        image: travisrowland/dockercakephp_php:latest
        expose:
            - "9000"
        volumes_from:
            - cakephp
        volumes:
            - /www/app/logs
        links:
            - db
            - cakephp
        environment:
          DEBUG: 'true'
          DB_HOST: 'db' # Leave this as 'db' to utilize MySQL container(s)
          DB_USERNAME: 'root'
          DB_PASSWORD: 'cakephp'
          DB_DATABASE: 'cakephp'
          DB_SEED: 'DatabaseSeed'
          EMAIL_HOST: 'localhost'
          EMAIL_PORT: '25'
          EMAIL_TIMEOUT: '30'
          EMAIL_USERNAME: 'user'
          EMAIL_PASSWORD: 'secret'
          EMAIL_TLS:
          EMAIL_TRANSPORT_DEFAULT_URL:
    cakephp:
        image: travisrowland/cakephp-bookmarker:latest
        volumes:
            - /www
    nginx:
        image: travisrowland/dockercakephp_nginx
        ports:
            - "80:80"
        links:
            - php
            - cakephp
        volumes_from:
            - cakephp
        volumes:
            - ./logs/nginx/:/var/log/nginx
