version: '2'
services:
    db:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
          MYSQL_ROOT_PASSWORD: 'cakephp'
          MYSQL_DATABASE: 'cakephp'
    php:
        image: travisrowland/dockercakephp_php:latest
        expose:
            - "9000"
        volumes_from:
            - cakephp-bookmarker
        volumes:
            - /www/app/logs
        links:
            - db
            - cakephp-bookmarker
        environment:
          DB_USERNAME: 'root'
          DB_PASSWORD: 'cakephp'
          DB_DATABASE: 'cakephp'
          DB_SEED: 'DatabaseSeed'
    cakephp-bookmarker:
        image: travisrowland/cakephp-bookmarker:latest
        volumes:
            - /www
    nginx:
        image: travisrowland/dockercakephp_nginx
        ports:
            - "80:80"
        links:
            - php
            - cakephp-bookmarker
        volumes_from:
            - cakephp-bookmarker
        volumes:
            - ./logs/nginx/:/var/log/nginx
